// Generated by CoffeeScript 1.9.1
(function() {
  var Migrator, StoneSkin, Store, clone, uuid,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Store = require('idb-wrapper-promisify');

  uuid = require('node-uuid');

  clone = require('clone');

  module.exports = StoneSkin = {};

  StoneSkin.validate = function(data, schema) {
    console.warn('StoneSkin.validate is not set');
    return true;
  };

  StoneSkin.Base = (function() {
    Base.prototype.name = null;

    function Base() {}

    Base.prototype.save = function() {
      throw new Error('you should override');
    };

    Base.prototype.find = function() {
      throw new Error('you should override');
    };

    Base.prototype.first = function() {
      throw new Error('you should override');
    };

    Base.prototype.last = function() {
      throw new Error('you should override');
    };

    Base.prototype.select = function() {
      throw new Error('you should override');
    };

    Base.prototype.clear = function() {
      throw new Error('you should override');
    };

    Base.prototype._ensureId = function(data) {
      var cloned;
      if (data._id != null) {
        return data;
      } else {
        cloned = clone(data);
        cloned._id = uuid();
        return cloned;
      }
    };

    Base.prototype.validate = function(data) {
      return StoneSkin.validate(data, this.schema);
    };

    Base.prototype.createValidateReason = function(data) {
      return StoneSkin.createValidateReason(data, this.schema);
    };

    return Base;

  })();

  StoneSkin.SyncedMemoryDb = (function(superClass) {
    extend(SyncedMemoryDb, superClass);

    function SyncedMemoryDb() {
      SyncedMemoryDb.__super__.constructor.apply(this, arguments);
      this._data = [];
    }

    SyncedMemoryDb.prototype._pushOrUpdate = function(data) {
      var ensured, found, k, v;
      found = this._find(data._id);
      if (!!found) {
        for (k in data) {
          v = data[k];
          found[k] = v;
        }
        return found;
      } else {
        ensured = this._ensureId(data);
        this._data.push(ensured);
        return ensured;
      }
    };

    SyncedMemoryDb.prototype.save = function(data) {
      var d, existIds, i, j, len, reason, result, valid;
      existIds = this._data.map(function(d) {
        return d._id;
      });
      if (data instanceof Array) {
        if (this.schema && !!this.skipValidate === false) {
          for (j = 0, len = data.length; j < len; j++) {
            d = data[j];
            reason = this.createValidateReason(d);
            if (!reason.valid) {
              throw reason.error;
            }
          }
        }
        result = (function() {
          var l, len1, results;
          results = [];
          for (l = 0, len1 = data.length; l < len1; l++) {
            i = data[l];
            results.push(this._pushOrUpdate(i));
          }
          return results;
        }).call(this);
        return result;
      } else {
        valid = this.validate(data);
        if (!valid) {
          reason = this.createValidateReason(data);
          throw reason.error;
        }
        return this._pushOrUpdate(data);
      }
    };

    SyncedMemoryDb.prototype._find = function(id) {
      var item, j, len, ref;
      ref = this._data;
      for (j = 0, len = ref.length; j < len; j++) {
        item = ref[j];
        if (item._id === id) {
          return item;
        }
      }
      return void 0;
    };

    SyncedMemoryDb.prototype.find = function(id) {
      return this._find(id);
    };

    SyncedMemoryDb.prototype.remove = function(id) {
      if (id instanceof Array) {
        this._data = this._data.filter(function(i) {
          var ref;
          return ref = i._id, indexOf.call(id, ref) < 0;
        });
      } else {
        this._data = this._data.filter(function(i) {
          return i._id !== id;
        });
      }
      return void 0;
    };

    SyncedMemoryDb.prototype.first = function(fn) {
      var item, j, len, ref;
      ref = this._data;
      for (j = 0, len = ref.length; j < len; j++) {
        item = ref[j];
        if (fn(item)) {
          return item;
        }
      }
      return void 0;
    };

    SyncedMemoryDb.prototype.last = function(fn) {
      var item, j, len, ref;
      ref = this._data.reverse();
      for (j = 0, len = ref.length; j < len; j++) {
        item = ref[j];
        if (fn(item)) {
          return item;
        }
      }
      return void 0;
    };

    SyncedMemoryDb.prototype.select = function(fn) {
      var i, j, len, ref, result;
      result = [];
      ref = this._data;
      for (j = 0, len = ref.length; j < len; j++) {
        i = ref[j];
        if (fn(i)) {
          result.push(i);
        }
      }
      return clone(this._data.filter(function(i) {
        return fn(i);
      }));
    };

    SyncedMemoryDb.prototype.clear = function() {
      return this._data.length = 0;
    };

    SyncedMemoryDb.prototype.all = function() {
      return clone(this._data);
    };

    return SyncedMemoryDb;

  })(StoneSkin.Base);

  StoneSkin.MemoryDb = (function(superClass) {
    extend(MemoryDb, superClass);

    function MemoryDb() {
      MemoryDb.__super__.constructor.apply(this, arguments);
      this.ready = Promise.resolve();
    }

    MemoryDb.prototype.save = function() {
      var e;
      try {
        return Promise.resolve(MemoryDb.__super__.save.apply(this, arguments));
      } catch (_error) {
        e = _error;
        return Promise.reject(e);
      }
    };

    MemoryDb.prototype.remove = function() {
      return Promise.resolve(MemoryDb.__super__.remove.apply(this, arguments));
    };

    MemoryDb.prototype.find = function() {
      return Promise.resolve(MemoryDb.__super__.find.apply(this, arguments));
    };

    MemoryDb.prototype.first = function() {
      return Promise.resolve(MemoryDb.__super__.first.apply(this, arguments));
    };

    MemoryDb.prototype.select = function() {
      return Promise.resolve(MemoryDb.__super__.select.apply(this, arguments));
    };

    MemoryDb.prototype.clear = function() {
      return Promise.resolve(MemoryDb.__super__.clear.apply(this, arguments));
    };

    MemoryDb.prototype.all = function() {
      return Promise.resolve(MemoryDb.__super__.all.apply(this, arguments));
    };

    return MemoryDb;

  })(StoneSkin.SyncedMemoryDb);

  StoneSkin.IndexedDb = (function(superClass) {
    extend(IndexedDb, superClass);

    IndexedDb.prototype.keyPath = '_id';

    function IndexedDb() {
      IndexedDb.__super__.constructor.apply(this, arguments);
      this._store = new Store({
        storeName: this.storeName,
        keyPath: this.keyPath
      });
      this.ready = this._store.ready;
    }

    IndexedDb.prototype.clear = function() {
      return this._store.clear();
    };

    IndexedDb.prototype.select = function(fn) {
      var result;
      result = [];
      return this._store.iterate(function(i) {
        if (fn(i)) {
          return result.push(i);
        }
      }).then(function() {
        return result;
      });
    };

    IndexedDb.prototype.first = function(fn) {
      return this.select(fn).then((function(_this) {
        return function(items) {
          return items[0];
        };
      })(this));
    };

    IndexedDb.prototype.last = function(fn) {
      return this.select(fn).then((function(_this) {
        return function(items) {
          return items[items.length - 1];
        };
      })(this));
    };

    IndexedDb.prototype._saveBatch = function(list) {
      var data, j, len, reason, result;
      if (this.schema && !!this.skipValidate === false) {
        for (j = 0, len = list.length; j < len; j++) {
          data = list[j];
          reason = this.createValidateReason(data);
          if (!reason.valid) {
            return Promise.reject(reason.error);
          }
        }
      }
      result = list.map((function(_this) {
        return function(i) {
          return _this._ensureId(i);
        };
      })(this));
      return this._store.putBatch(result).then(function() {
        return result;
      });
    };

    IndexedDb.prototype.save = function(data) {
      var isValid, reason, result;
      if (data instanceof Array) {
        return this._saveBatch(data);
      }
      if (this.schema && !!this.skipValidate === false) {
        isValid = this.validate(data);
        if (!isValid) {
          reason = this.createValidateReason(data);
          return Promise.reject(reason.error);
        }
      }
      result = this._ensureId(data);
      return this._store.put(result).then(function() {
        return result;
      });
    };

    IndexedDb.prototype.remove = function(id) {
      if (id instanceof Array) {
        return this._store.removeBatch(id);
      } else {
        return this._store.remove(id);
      }
    };

    IndexedDb.prototype.find = function(id) {
      return this._store.get(id)["catch"](function(e) {
        return void 0;
      });
    };

    IndexedDb.prototype.all = function() {
      return this._store.getAll();
    };

    IndexedDb.prototype.toMemoryDb = function() {
      return this._store.getAll().then((function(_this) {
        return function(items) {
          var memoryDb;
          memoryDb = new ((function(superClass1) {
            extend(_Class, superClass1);

            function _Class() {
              return _Class.__super__.constructor.apply(this, arguments);
            }

            _Class.prototype.name = _Class.name;

            _Class.prototype.schema = _Class.schema;

            return _Class;

          })(StoneSkin.MemoryDb));
          memoryDb._data = items;
          return memoryDb;
        };
      })(this));
    };

    IndexedDb.prototype.toSyncedMemoryDb = function() {
      return this._store.getAll().then((function(_this) {
        return function(items) {
          var memoryDb;
          memoryDb = new ((function(superClass1) {
            extend(_Class, superClass1);

            function _Class() {
              return _Class.__super__.constructor.apply(this, arguments);
            }

            _Class.prototype.name = _Class.name;

            _Class.prototype.schema = _Class.schema;

            return _Class;

          })(SyncedMemoryDb));
          memoryDb._data = items;
          return memoryDb;
        };
      })(this));
    };

    return IndexedDb;

  })(StoneSkin.Base);

  Migrator = (function() {
    function Migrator(version, opts1) {
      this.version = version;
      this.opts = opts1 != null ? opts1 : {};
      this._migrateByVersion = bind(this._migrateByVersion, this);
      this.lastVersion = this.getLastVersion();
      this.needInitialize = !this.lastVersion;
    }

    Migrator.prototype.getLastVersion = function() {
      return typeof localStorage !== "undefined" && localStorage !== null ? localStorage.getItem('ss-dbVersion') : void 0;
    };

    Migrator.prototype.needUpdated = function() {
      if ((this.lastVersion != null) && this.lastVersion === this.version) {
        return false;
      } else {
        return true;
      }
    };

    Migrator.prototype._setDbVersionToLocalStorage = function() {
      return typeof localStorage !== "undefined" && localStorage !== null ? localStorage.setItem('ss-dbVersion', this.version) : void 0;
    };

    Migrator.prototype.migrate = function() {
      var base;
      return Promise.resolve(this.needInitialize ? (this._setDbVersionToLocalStorage(), typeof (base = this.opts).initialize === "function" ? base.initialize() : void 0) : null).then((function(_this) {
        return function() {
          if (_this.needUpdated()) {
            return _this._migrateByVersion(_this.lastVersion, _this.version).then(function() {
              return _this._setDbVersionToLocalStorage();
            });
          }
        };
      })(this));
    };

    Migrator.prototype._migrateByVersion = function(from, to) {
      var fn, fnName, start;
      from = parseInt(from, 10);
      to = parseInt(to, 10);
      start = Promise.resolve();
      while (from < to) {
        fnName = from + "to" + (from + 1);
        fn = this.opts[fnName];
        start = start.then(fn);
        from++;
      }
      return start;
    };

    return Migrator;

  })();

  StoneSkin.utils = {};

  StoneSkin.utils.setupWithMigrate = function(currentVersion, opts) {
    var migrator;
    if (opts == null) {
      opts = {};
    }
    migrator = new Migrator(currentVersion, opts);
    return migrator.migrate();
  };

}).call(this);
