// Generated by CoffeeScript 1.9.1
(function() {
  var SS, tv4;

  SS = require('./index');

  tv4 = require('tv4');

  SS.validate = function(data, schema) {
    return {
      validate: function(data) {
        return tv4.validate(data, schema, true);
      }
    };
  };

  module.exports = SS;

}).call(this);
