// Generated by CoffeeScript 1.9.1
(function() {
  var StoneSkin, tv4;

  StoneSkin = require('./index');

  tv4 = require('tv4');

  StoneSkin.validate = function(data, schema) {
    return {
      validate: function(data) {
        return tv4.validate(data, schema, true);
      }
    };
  };

  module.exports = StoneSkin;

}).call(this);
