// Generated by CoffeeScript 1.9.1
(function() {
  var StoneSkin, tv4;

  StoneSkin = require('./index');

  tv4 = require('tv4');

  StoneSkin.validate = function(data, schema) {
    return tv4.validate(data, schema != null ? schema : {}, true);
  };

  StoneSkin.createValidateReason = function(data, schema) {
    return tv4.validateResult(data, schema != null ? schema : {}, true);
  };

  module.exports = StoneSkin;

}).call(this);
